name: Preflight Label Issue In Develop
on: 
  pull_request:
    branches: [develop]
    types: [closed]
jobs:
  label_preflight:
    name: Preflight Label Issue In Develop
    runs-on: ubuntu-18.04
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python v3.8
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8

      - name: Install dependencies 
        run: |
          python -m pip install --upgrade pip
          pip install -r ./.github/scripts/requirements.txt
          
      - name: Save the PR body in an artifact
        shell: bash
        env:
          PR_BODY: ${{ github.event.number }}
        run: echo $PR_BODY > pr_body.txt

      - name: Upload the PR body
        uses: actions/upload-artifact@v2.2.4
        with:
          name: pr_body
          path: ./pr_body.txt
